[package]
name = "stsearch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
tree-sitter = "0.20"
tree-sitter-javascript = "0.20"

[build-dependencies]
cc = "1.0"
tree-sitter = "0.20"
tree-sitter-cli = "0.20"
